//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace MartinCostello.LondonTravel.Skill {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "16.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class Strings {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Strings() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("MartinCostello.LondonTravel.Skill.Strings", typeof(Strings).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to You need to link your account to be able to ask me about your commute..
        /// </summary>
        internal static string CommuteIntentAccountNotLinked {
            get {
                return ResourceManager.GetString("CommuteIntentAccountNotLinked", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Your Commute.
        /// </summary>
        internal static string CommuteIntentCardTitle {
            get {
                return ResourceManager.GetString("CommuteIntentCardTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to It looks like you&apos;ve disabled account linking. You need to re-link your account to be able to ask me about your commute..
        /// </summary>
        internal static string CommuteIntentInvalidToken {
            get {
                return ResourceManager.GetString("CommuteIntentInvalidToken", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to You have not selected any favorite lines yet. Visit the London Travel website to set your preferences..
        /// </summary>
        internal static string CommuteIntentNoFavorites {
            get {
                return ResourceManager.GetString("CommuteIntentNoFavorites", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to {0}: {1}.
        /// </summary>
        internal static string CommuteIntentPrefixFormat {
            get {
                return ResourceManager.GetString("CommuteIntentPrefixFormat", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Disruption Summary.
        /// </summary>
        internal static string DisruptionIntentCardTitle {
            get {
                return ResourceManager.GetString("DisruptionIntentCardTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to There is a good service on all other lines..
        /// </summary>
        internal static string DisruptionIntentGoodServiceOnOtherLines {
            get {
                return ResourceManager.GetString("DisruptionIntentGoodServiceOnOtherLines", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to There is currently no disruption on the tube, London Overground, the DLR or TfL Rail..
        /// </summary>
        internal static string DisruptionIntentNoDisruption {
            get {
                return ResourceManager.GetString("DisruptionIntentNoDisruption", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to This skill allows you to check for the status of a specific line, or for disruption in general. You can ask about any London Underground line, London Overground, the Docklands Light Railway or TfL Rail..
        /// </summary>
        internal static string HelpIntentParagraph1 {
            get {
                return ResourceManager.GetString("HelpIntentParagraph1", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Asking about disruption in general provides information about any lines that are currently experiencing issues, such as any delays or planned closures..
        /// </summary>
        internal static string HelpIntentParagraph2 {
            get {
                return ResourceManager.GetString("HelpIntentParagraph2", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Asking for the status for a specific line provides a summary of the current service, such as whether there is a good service or if there are any delays..
        /// </summary>
        internal static string HelpIntentParagraph3 {
            get {
                return ResourceManager.GetString("HelpIntentParagraph3", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to If you link your account and setup your preferences in the London Travel website, you can ask about your commute to quickly find out the status of the lines you frequently use..
        /// </summary>
        internal static string HelpIntentParagraph4 {
            get {
                return ResourceManager.GetString("HelpIntentParagraph4", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Sorry, something went wrong..
        /// </summary>
        internal static string InternalError {
            get {
                return ResourceManager.GetString("InternalError", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Welcome to London Travel. You can ask me about disruption or for the status of any tube line, London Overground, the DLR or TfL Rail..
        /// </summary>
        internal static string LaunchResponse {
            get {
                return ResourceManager.GetString("LaunchResponse", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to {0}{1}.
        /// </summary>
        internal static string LineNameWithoutPrefixFormat {
            get {
                return ResourceManager.GetString("LineNameWithoutPrefixFormat", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to {0}{1}{2}.
        /// </summary>
        internal static string LineNameWithPrefixFormat {
            get {
                return ResourceManager.GetString("LineNameWithPrefixFormat", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to  line.
        /// </summary>
        internal static string LineSuffixLower {
            get {
                return ResourceManager.GetString("LineSuffixLower", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to  Line.
        /// </summary>
        internal static string LineSuffixUpper {
            get {
                return ResourceManager.GetString("LineSuffixUpper", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Goodbye..
        /// </summary>
        internal static string SessionEndResponse {
            get {
                return ResourceManager.GetString("SessionEndResponse", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Some parts of {0} are currently being served by a replacement bus service..
        /// </summary>
        internal static string StatusIntentBusServiceFormat {
            get {
                return ResourceManager.GetString("StatusIntentBusServiceFormat", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to {0}{1} Status.
        /// </summary>
        internal static string StatusIntentCardTitleFormat {
            get {
                return ResourceManager.GetString("StatusIntentCardTitleFormat", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to {0} is closed..
        /// </summary>
        internal static string StatusIntentClosedFormat {
            get {
                return ResourceManager.GetString("StatusIntentClosedFormat", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Sorry, I cannot tell you about the status of the Elizabeth Line yet..
        /// </summary>
        internal static string StatusIntentElizabethLineNotImplemented {
            get {
                return ResourceManager.GetString("StatusIntentElizabethLineNotImplemented", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to There is currently disruption on {0}..
        /// </summary>
        internal static string StatusIntentGenericDisruptionFormat {
            get {
                return ResourceManager.GetString("StatusIntentGenericDisruptionFormat", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to There is a good service on {0}..
        /// </summary>
        internal static string StatusIntentGoodServiceFormat {
            get {
                return ResourceManager.GetString("StatusIntentGoodServiceFormat", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to There are minor delays on {0}..
        /// </summary>
        internal static string StatusIntentMinorDelaysFormat {
            get {
                return ResourceManager.GetString("StatusIntentMinorDelaysFormat", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to {0} is partially closed..
        /// </summary>
        internal static string StatusIntentPartiallyClosedFormat {
            get {
                return ResourceManager.GetString("StatusIntentPartiallyClosedFormat", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to {0} is partially suspended..
        /// </summary>
        internal static string StatusIntentPartiallySuspendedFormat {
            get {
                return ResourceManager.GetString("StatusIntentPartiallySuspendedFormat", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to There is a planned closure on {0}..
        /// </summary>
        internal static string StatusIntentPlannedClosureFormat {
            get {
                return ResourceManager.GetString("StatusIntentPlannedClosureFormat", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to There is a reduced service on {0}..
        /// </summary>
        internal static string StatusIntentReducedServiceFormat {
            get {
                return ResourceManager.GetString("StatusIntentReducedServiceFormat", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to There are severe delays on {0}..
        /// </summary>
        internal static string StatusIntentSevereDelaysFormat {
            get {
                return ResourceManager.GetString("StatusIntentSevereDelaysFormat", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to {0} is suspended..
        /// </summary>
        internal static string StatusIntentSuspendedFormat {
            get {
                return ResourceManager.GetString("StatusIntentSuspendedFormat", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Sorry, I am not sure what line you said. You can ask about the status of any tube line, London Overground, the DLR or TfL Rail..
        /// </summary>
        internal static string StatusIntentUnknownLine {
            get {
                return ResourceManager.GetString("StatusIntentUnknownLine", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to the .
        /// </summary>
        internal static string ThePrefix {
            get {
                return ResourceManager.GetString("ThePrefix", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Sorry, I don&apos;t understand how to do that..
        /// </summary>
        internal static string UnknownCommand {
            get {
                return ResourceManager.GetString("UnknownCommand", resourceCulture);
            }
        }
    }
}
