version: 2
updates:
- package-ecosystem: "github-actions"
  directory: "/"
  schedule:
    interval: daily
    time: "05:30"
    timezone: Europe/London
  reviewers:
    - "martincostello"
- package-ecosystem: nuget
  directory: "/"
  groups:
    opentelemetry:
      patterns:
        - OpenTelemetry*
    polly:
      patterns:
        - Polly*
    xunit:
      patterns:
        - xunit*
  schedule:
    interval: daily
    time: "05:30"
    timezone: Europe/London
  reviewers:
    - "martincostello"
  open-pull-requests-limit: 99
  ignore:
    - dependency-name: "AWSSDK*"
- package-ecosystem: nuget
  directory: "/"
  groups:
    awssdk:
      patterns:
        - AWSSDK*
  schedule:
    interval: monthly
    time: "05:30"
    timezone: Europe/London
  reviewers:
    - "martincostello"
  open-pull-requests-limit: 99
  allow:
    - dependency-name: "AWSSDK*"
