version: 2
updates:
- package-ecosystem: "github-actions"
  directory: "/"
  schedule:
    interval: daily
    time: "05:30"
    timezone: Europe/London
  reviewers:
    - "martincostello"
- package-ecosystem: nuget
  directory: "/"
  groups:
    Amazon.Lambda:
      patterns:
        - Amazon.Lambda.*
    AWSSDK:
      patterns:
        - AWSSDK*
    Microsoft.Extensions:
      patterns:
        - Microsoft.Extensions.*
    MSTest:
      patterns:
        - MSTest.Sdk
        - MSTest.TestFramework
    OpenTelemetry:
      patterns:
        - OpenTelemetry*
    Polly:
      patterns:
        - Polly*
    xunit:
      patterns:
        - xunit*
  schedule:
    interval: daily
    time: "05:30"
    timezone: Europe/London
  reviewers:
    - "martincostello"
  open-pull-requests-limit: 99
  ignore:
    - dependency-name: "AWSSDK*"
      update-types: ["version-update:semver-patch"]
