version: 2
updates:
- package-ecosystem: nuget
  directory: "/"
  schedule:
    interval: yearly
    timezone: Europe/London
  ignore:
    - dependency-name: "AWSSDK*"
      update-types: ["version-update:semver-patch"]
